# Generated by Django 5.2.4 on 2025-07-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_welderprofile_weldingsession_predictionresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="welderprofile",
            name="certification_body",
            field=models.CharField(
                blank=True, help_text="Lembaga penerbit sertifikasi", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="welderprofile",
            name="certification_expiry",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="welderprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="welderprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="welderprofile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="welder_photos/"),
        ),
        migrations.AddField(
            model_name="welderprofile",
            name="skills",
            field=models.TextField(
                blank=True,
                help_text="Jenis pengelasan yang dikuasai, misal: SMAW, TIG, MIG",
            ),
        ),
        migrations.AlterField(
            model_name="welderprofile",
            name="experience_years",
            field=models.IntegerField(default=0),
        ),
    ]
