# Generated by Django 5.2 on 2025-08-26 23:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_welderprofile_certification_body_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="predictionresult",
            name="session",
        ),
        migrations.RemoveField(
            model_name="predictionresult",
            name="window_end",
        ),
        migrations.RemoveField(
            model_name="predictionresult",
            name="window_start",
        ),
        migrations.DeleteModel(
            name="WeldingSession",
        ),
    ]
