# Generated by Django 5.2 on 2025-08-27 00:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_remove_predictionresult_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="predictionresult",
            name="window_end",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="predictionresult",
            name="window_start",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
